name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Constructores
      id: test-constructores
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: sudo -H pip3 install pytest
    - name: Test Atributos
      id: test-atributos
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: sudo -H pip3 install pytest
    - name: Test Metodos
      id: test-metodos
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CONSTRUCTORES_RESULTS: "${{steps.test-constructores.outputs.result}}"
        TEST-ATRIBUTOS_RESULTS: "${{steps.test-atributos.outputs.result}}"
        TEST-METODOS_RESULTS: "${{steps.test-metodos.outputs.result}}"
      with:
        runners: test-constructores,test-atributos,test-metodos
